### ISSUE TITLE
Custom indexing for selected fields (human readable/facetable versions)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#369]
For selected metadata fields that we populate, we will want to create custom indexing behaviors in order to display or facet them in a more human readable format.

- [x] **creator**

- We want the ability to create an Author facet that will list authors as _Lastname, Firstname_ only

- [x] **date_issued**

We want the ability to facet (or use a date range slider) these dates only using their 4-digit year (YYYY) value

**Comment by abelemlih** [comment]
PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/388/files

@eporter23 before I proceed forward with PR approval, I want to confirm the following:

For the facet fields to get indexed correctly, I need to add a predicate for each. Here are the fields I added and their predicates, does that meet your expectations?

```
creator_last_first:
    type: string
    multiple: true
    ordered: true
    form:
      required: false
      primary: true
      multiple: true
    index_keys:
      - "creator_last_first_tesim"
      - "creator_last_first_ssim"
    predicate: http://metadata.emory.edu/vocab/cor-terms#creatorLastFirst
```

```
date_issued_year:
    type: string
    multiple: false
    form:
      primary: true
      multiple: false
      required: false
    index_keys:
      - 'date_issued_year_tesi'
      - 'date_issued_year_ssi'
    predicate: http://metadata.emory.edu/vocab/cor-terms#issuedYear
```
